Add Pp.Ast
ocaml-dune/pp pull request #6
Opened 2021-03-26 23:05 UTC by rgrinberg

Since we've introduced the injection of Format, we need a specialized type to
serialize Pp values. The introduction of Pp.Ast.t attempts to solve this.

I could have also shared the constructors of Pp.Ast.t and Pp.t.

2021-03-26 23:10 UTC, rgrinberg commented
In retrospect, maybe adding `Format` was a mistake after all. It complicates serialization without pulling its weight.

2021-03-28 21:51 UTC, rgrinberg commented
@Drup perhaps it's possible to change Format.t to a more initial encoding like Pp.t? It seems like a serious limitation that one cannot serialize and preserve the meaning of such values.

2021-03-28 22:15 UTC, Drup commented
> @Drup perhaps it's possible to change Format.t to a more initial encoding like Pp.t? It seems like a serious limitation that one cannot serialize and preserve the meaning of such values.

If it were designed today, yes, certainly. It's rather difficult to add now, given how `%t`/`%a` work, and their interaction with side effects. Closures are pretty much baked in. For a while I had a prototype of an `Xprintf` function that would return such a structured representation without closures, but it doesn't really work.

2021-03-29 07:57 UTC, jeremiedimino commented
> In retrospect, maybe adding Format was a mistake after all. It complicates serialization without pulling its weight.

What about `to_ast` fails when it encounter the `Format` constructor? After all, serialisation is a new feature of `Pp` and it seems ok to me to say that you have to be completely in the `Pp` world to use it.

FTR, independently of the discussion about Format, I think having this separate AST type is better as it means we are free to change the representation of `Pp.t` values without breaking backward compatibility.

2021-03-29 08:27 UTC, rgrinberg commented
> What about to_ast fails when it encounter the Format constructor?

The `to_ast` in this PR allows for that. Just raise an exception inside the callback for Format values.

2021-03-29 09:14 UTC, jeremiedimino commented
Indeed. But in practice, do we have anything meaningful to put in this callback? If all the use sites are just raising, then it feels superfluous.

And more generally, if we are able to turn a `Format.formtter -> unit` into an ast at the `to_ast` stage, then why not do it immediately instead of calling `of_fmt`?

2021-03-29 09:22 UTC, rgrinberg commented
> And more generally, if we are able to turn a Format.formtter -> unit into an ast at the to_ast stage, then why not do it immediately instead of calling of_fmt?

That's a good point. I changed the function to return a result.

2021-03-29 09:28 UTC, jeremiedimino requested changes
Looks good. Could just use a comment to say what these functions are for. And also explain what `to_ast` returning `Error ()` means

2021-03-29 09:34 UTC, rgrinberg commented
done

2021-03-29 10:26 UTC, jeremiedimino approved these changes
Looks good

2021-03-29 19:10 UTC, merged